In [ ]:
import torch

## Operations on Tensor

In [ ]:
# Defining basic Tensors
x1=torch.rand(2,2)
x2=torch.rand(2,2)
print(x1), print(x2)

tensor([[0.4115, 0.6839],
        [0.0703, 0.5105]])
tensor([[0.9451, 0.2359],
        [0.1979, 0.3327]])


(None, None)

### Performing Scalar operations on single tensor

In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
print((x1-2)*5) # Subtract 2 from all elements and multiply by 5

tensor([[-7.9426, -6.5807],
        [-9.6487, -7.4474]])


In [ ]:
x1=x1-10
print("Original Value of x1:", x1)
print('\nAbsolute value of r:')
print(torch.abs(x1))

Original Value of x1: tensor([[-9.5885, -9.3161],
        [-9.9297, -9.4895]])

Absolute value of r:
tensor([[9.5885, 9.3161],
        [9.9297, 9.4895]])


In [ ]:
r=x2
# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))


Inverse sine of r:
tensor([[1.2378, 0.2381],
        [0.1992, 0.3392]])

Determinant of r:
tensor(0.2678)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.9573, -0.2892],
        [-0.2892,  0.9573]]),
S=tensor([1.0144, 0.2640]),
V=tensor([[-0.9483, -0.3174],
        [-0.3174,  0.9483]]))

Average and standard deviation of r:
(tensor(0.3494), tensor(0.4279))

Maximum value of r:
tensor(0.9451)


### Performing Vector Operations on Tensor

In [ ]:
# Addition of two tensors
x3=x1+x2
x3=torch.add(x1,x2)
print('x1+x2=x3'+x1+"+"+x2+"="+x3)

TypeError: can only concatenate str (not "Tensor") to str

In [ ]:
# Add value to x, an change value(_ after function makes changes in variable)
x2.add_(x1)

# Subtraction
x4=x2-x1
x4=torch.sub(x1,x2)

In [ ]:
# Multiplication
x5=x2*x1
x5=torch.mul(x1,x2)

# Division
x6=x2/x1
x6=torch.div(x1,x2)