In [2]:
import torch

In [3]:
## To reshape a tensor, there are several methods available.
x1=torch.randn(2,3,4)
print(x1)
print(x1.size())


tensor([[[-1.3661,  0.6346,  0.1168, -1.1562],
         [ 0.9549,  2.7669, -0.1460, -1.1923],
         [-2.4166, -0.5575, -0.1595, -0.3779]],

        [[ 0.1521,  0.9622, -1.8090,  0.3845],
         [ 1.6780, -0.7819,  0.6705,  0.8674],
         [ 1.2633,  1.0293, -0.7091,  1.2727]]])
torch.Size([2, 3, 4])


In [4]:
# Method-1 : - Using view() method
x1_view=x1.view(2,12)
print(x1_view)
print(x1_view.size())

tensor([[-1.3661,  0.6346,  0.1168, -1.1562,  0.9549,  2.7669, -0.1460, -1.1923,
         -2.4166, -0.5575, -0.1595, -0.3779],
        [ 0.1521,  0.9622, -1.8090,  0.3845,  1.6780, -0.7819,  0.6705,  0.8674,
          1.2633,  1.0293, -0.7091,  1.2727]])
torch.Size([2, 12])


In [21]:
# You can also use -1 to infer the size of one dimension
x2_view=x1.view(3,-1)
print(x2_view.shape)

torch.Size([3, 8])


In [ ]:
# Method-2: - Using unsqueeze() method
# The unsqueeze() method adds a dimension of extent 1. unsqueeze(0) adds it as a new zeroth dimension - now you have a batch of one!
# The unqsueeze(1) adds it as the first dimension, and so on.
# Basically the unsqueeze method takes the index of the dimension you want to add and adds it as a new dimension.

x = torch.rand(3, 226, 226)
print("Original Shape",x.shape)
x = x.unsqueeze(0)
print("Shape after unsqueeze(0)",x.shape)
print(x)
print("Shape after unsqueeze(3)",x.unsqueeze(3).shape)

Original Shape torch.Size([3, 226, 226])
Shape after unsqueeze(0) torch.Size([1, 3, 226, 226])
tensor([[[[0.2418, 0.1209, 0.9333,  ..., 0.4434, 0.7505, 0.4618],
          [0.9685, 0.2189, 0.7590,  ..., 0.8405, 0.1660, 0.4205],
          [0.3107, 0.8769, 0.3714,  ..., 0.7730, 0.3236, 0.4696],
          ...,
          [0.5068, 0.4148, 0.3646,  ..., 0.7379, 0.7623, 0.3199],
          [0.2004, 0.1082, 0.8174,  ..., 0.0166, 0.6501, 0.8799],
          [0.1199, 0.0561, 0.3592,  ..., 0.9152, 0.1133, 0.8859]],

         [[0.3461, 0.9956, 0.0943,  ..., 0.6121, 0.6805, 0.5320],
          [0.5685, 0.8532, 0.5558,  ..., 0.1218, 0.7122, 0.5459],
          [0.3922, 0.4420, 0.8524,  ..., 0.2882, 0.1139, 0.1862],
          ...,
          [0.4736, 0.5190, 0.2122,  ..., 0.9093, 0.3334, 0.4955],
          [0.3826, 0.3988, 0.1167,  ..., 0.8257, 0.3649, 0.6493],
          [0.1050, 0.5908, 0.9890,  ..., 0.6614, 0.5766, 0.1885]],

         [[0.8250, 0.8137, 0.0911,  ..., 0.5003, 0.1769, 0.1661],
          [0.

In [14]:
# Method-3: - Using squeeze() method

x= torch.rand(1, 20)
print("Original Shape",x.shape)
print(x)
print("Shape after squeeze(0)",x.squeeze(0).shape)
print(x.squeeze(0))

# Note : - 
# You may only squeeze() dimensions of extent 1. See above where we try to squeeze a dimension of size 2 in c, and get back the same shape we started with. 
# Calls to squeeze() and unsqueeze() can only act on dimensions of extent 1 because to do otherwise would change the number of elements in the tensor.

Original Shape torch.Size([1, 20])
tensor([[0.7520, 0.2768, 0.3315, 0.6909, 0.1261, 0.1157, 0.9555, 0.0650, 0.9761,
         0.4292, 0.6884, 0.7489, 0.7745, 0.8374, 0.2852, 0.2947, 0.8555, 0.5285,
         0.1198, 0.9310]])
Shape after squeeze(0) torch.Size([20])
tensor([0.7520, 0.2768, 0.3315, 0.6909, 0.1261, 0.1157, 0.9555, 0.0650, 0.9761,
        0.4292, 0.6884, 0.7489, 0.7745, 0.8374, 0.2852, 0.2947, 0.8555, 0.5285,
        0.1198, 0.9310])


In [17]:
## Method 4: - Using Permute() method
x=torch.rand(2,3,4)
print(x, x.shape)

# The permute function is used to reorder the dimensions of the tensor. It takes the desired order of dimensions as arguments.
# Example: - say x has 3 dimensions (2,3,4) and you want to reorder them to (2,4,3) then you can use permute(0,2,1). 0,2,1 signifies 0th, 2nd and 1st dimension.

z = x.permute(0, 2, 1)  # Reorders dimensions
print("Post Permute")
print(z, z.shape)


tensor([[[0.8632, 0.8949, 0.1843, 0.4637],
         [0.3386, 0.9443, 0.0105, 0.5202],
         [0.9395, 0.7215, 0.4317, 0.6668]],

        [[0.1116, 0.2385, 0.7048, 0.4262],
         [0.6821, 0.9079, 0.0781, 0.1545],
         [0.3201, 0.7143, 0.2382, 0.9765]]]) torch.Size([2, 3, 4])
Post Permute
tensor([[[0.8632, 0.3386, 0.9395],
         [0.8949, 0.9443, 0.7215],
         [0.1843, 0.0105, 0.4317],
         [0.4637, 0.5202, 0.6668]],

        [[0.1116, 0.6821, 0.3201],
         [0.2385, 0.9079, 0.7143],
         [0.7048, 0.0781, 0.2382],
         [0.4262, 0.1545, 0.9765]]]) torch.Size([2, 4, 3])


In [18]:
x2=torch.randn(1,10)
print(x2)
print("Post Permute:", x2.permute(1,0))


tensor([[ 0.0480, -0.4201, -0.0834,  0.7209, -1.1456,  0.4769, -2.5682, -0.1019,
         -0.5168,  0.4965]])
Post Permute: tensor([[ 0.0480],
        [-0.4201],
        [-0.0834],
        [ 0.7209],
        [-1.1456],
        [ 0.4769],
        [-2.5682],
        [-0.1019],
        [-0.5168],
        [ 0.4965]])


In [20]:
# Method 5: - Using Flatten() method

x=torch.randn(2,3,4)
print("Original Shape",x.shape)
print("Post Flatten")
print(x.flatten(), x.flatten().shape)

Original Shape torch.Size([2, 3, 4])
Post Flatten
tensor([-0.0502,  2.0640,  0.4220,  0.5353, -0.7027, -0.9192, -0.2429,  1.7850,
         0.0170, -1.2968,  0.5875,  0.1563, -0.2008, -0.3261, -0.4684,  0.3127,
        -0.0094, -0.2043,  2.8271,  1.1605, -2.1868, -0.0929,  0.5267, -1.1337]) torch.Size([24])
